apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: end-to-end-gitops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: end-to-end-gitops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: end-to-end-gitops
            port:
              number: 80